// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPIcOxSWCkE1hoWMM4zu8VvfoqRJphHCw',
    appId: '1:1085876463007:web:6ca93ddf5e5acbf32749aa',
    messagingSenderId: '1085876463007',
    projectId: 'donation-app-a7e3f',
    authDomain: 'donation-app-a7e3f.firebaseapp.com',
    storageBucket: 'donation-app-a7e3f.appspot.com',
    measurementId: 'G-2G1QP3YQZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd-FO3ln8hdByls1opp3U1FlbuwS9aNpI',
    appId: '1:1085876463007:android:b9079197295f94d42749aa',
    messagingSenderId: '1085876463007',
    projectId: 'donation-app-a7e3f',
    storageBucket: 'donation-app-a7e3f.appspot.com',
  );
}